#!/usr/bin/env bash

function add_tag() {
  docker tag $IMAGE_NAME $DOCKER_REPO:$1
  docker push $DOCKER_REPO:$1
}

if [ "${DOCKER_TAG}" == "latest" ]; then
	CID=$(docker run -d $IMAGE_NAME)
	sleep 10s
	FG_VERSION=$(docker exec $CID flexget -V | sed -n 1p)
	docker rm -f $CID

	add_tag $FG_VERSION
fi

add_tag $DOCKER_TAG

exit $?
