name: docker-buildx

on:
  watch:
    types: [started]
  schedule:
    - cron: "0 21 * * 5"

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64,linux/arm/v7,linux/arm64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::transmission
          echo ::set-output name=version::$(pip3 search flexget | grep FlexGet | awk '{print $2}' | tr -d '()')
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Dockerhub Login
        env:
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          echo "${DOCKERHUB_PASS}" | docker login --username "${{ steps.vars.outputs.dockerhub_user }}" --password-stdin
      -
        name: Setup Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - 
        name: Run Buildx
        env:
          IMAGE_NAME: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --platform ${{ steps.vars.outputs.buildx_platforms }} \
            --tag "${IMAGE_NAME}:flexget-${{ steps.vars.outputs.version }}" \
            --tag "${IMAGE_NAME}:flexget" \
            --file Dockerfile . \
            --build-arg "ALPINE_VER=3.11" \
            --build-arg "FLEXGET_VER=${{ steps.vars.outputs.version }}" \
            --build-arg "LIBTORRENT_VER=1.2.6"
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: latest, ${{ steps.vars.outputs.version }}
