#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/flexget

# remove config-lock
[[ -f /flexget/.config-lock ]] && \
	rm -f /flexget/.config-lock

# copy config.yml
[[ ! -f /flexget/config.yml ]] && \
	cp /defaults/config.example.yml /flexget/config.yml

# permissions
chown -R abc:abc \
	/flexget

# set FG_WEBUI_PASSWD
if [[ ! -z "${FG_WEBUI_PASSWD}" ]]; then
	echo "Setting flexget web password to '${FG_WEBUI_PASSWD}'"
	RESULT=$(flexget -c /flexget/config.yml web passwd "${FG_WEBUI_PASSWD}" 2>&1)
	echo ${RESULT} | grep -q 'Updated password' && echo "${RESULT}" || \
		{ echo "${RESULT}"; exit 1; }
fi
